better answer a few questions
than safe 5 seconds of time and spend an hour to fix stuff later.

* i think it's much better to decide in the release process if we do a 0.11.3 release, or a 0.12

* also i got an error when doing the release (possibly due to the https changes on pypi combined with an older version of zest.releaser)

```
    utils.retry_twine('upload', server, *files_in_dist)
  File "/home/frisi/.buildout/eggs/zest.releaser-6.6.2-py2.7.egg/zest/releaser/utils.py", line 753, in retry_twine
    retry = retry_yes_no('twine %s' % twine_command)
  File "/home/frisi/.buildout/eggs/zest.releaser-6.6.2-py2.7.egg/zest/releaser/utils.py", line 777, in retry_yes_no
    raise RuntimeError(msg)
RuntimeError: The question 'Retry this command? [Yes/no/quit/?]' requires a manual answer, but we're running in --no-input mode.
```